services:
  db:
    container_name: kikapu_db
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresql2000
      POSTGRES_DB: kikapu_db
    volumes:
      - kikapu-postgres-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - kikapu-backend-network

  api:
    container_name: kikapu-backend-api
    build:
      context: ..
      dockerfile: docker/Dockerfile.prod
    restart: always
    env_file:
      - ../.env
    depends_on:
      db:
        condition: service_healthy
    environment:
      VIRTUAL_HOST: api-kikapu.eduwise-rdc.com
      LETSENCRYPT_HOST: api-kikapu.eduwise-rdc.com
      LETSENCRYPT_EMAIL: gedeonyalakuhanda@gmail.com
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgresql2000
      DB_DATABASE: kikapu_db
    ports:
      - '3005:3000'
    networks:
      - nginx-network
      - kikapu-backend-network

networks:
  nginx-network:
    external: true

  kikapu-backend-network:
    driver: bridge

volumes:
  kikapu-postgres-data:
